[package]
name = "rusty-git-mob"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
cursive = "0.20"
home = "0.5.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
git2 = "0.18.1"
regex = "1.10.4"
